# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy a Node.js app and an Angular app to Azure webservices

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npx nx run StardewConnect:build:production
          npx nx run StardewConnect-api:build:production
          npx nx run StardewConnect:test
        #npx nx run StardewConnect-api:test

      - name: Zip artifacts for deployment
        run: |
         echo ${GITHUB_WORKSPACE}
          cd ${GITHUB_WORKSPACE}/dist/apps/StardewConnect-api/ && zip -r ${GITHUB_WORKSPACE}/StardewConnect-api-release.zip .
          cd ${GITHUB_WORKSPACE}/dist/apps/StardewConnect/ && zip -r ${GITHUB_WORKSPACE}/StardewConnect-release.zip .
    
      - name: Upload frontend-app artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: StardewConnect
          path: StardewConnect-release.zip
          
      - name: Upload backend-api artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: StardewConnect-api
          path: StardewConnect-api-release.zip
          
          
  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: StardewConnect

      - name: Unzip artifact for deployment
        run: unzip StardewConnect-release.zip
        
      - name: Deploy to static azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.APP_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional


  deploy-backend-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: StardewConnect-api

      - name: Unzip artifact for deployment
        run: unzip StardewConnect-api-release.zip
       
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'StardewConnect-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.API_PUBLISHPROFILE }},
          package: .